use std::fmt;

pub enum Moon {
    MoonNew,
    MoonWaxingCrescent1,
    MoonWaxingCrescent2,
    MoonWaxingCrescent3,
    MoonWaxingCrescent4,
    MoonWaxingCrescent5,
    MoonWaxingCrescent6,
    MoonFirstQuarter,
    MoonWaxingGibbous1,
    MoonWaxingGibbous2,
    MoonWaxingGibbous3,
    MoonWaxingGibbous4,
    MoonWaxingGibbous5,
    MoonWaxingGibbous6,
    MoonFull,
    MoonWaningGibbous1,
    MoonWaningGibbous2,
    MoonWaningGibbous3,
    MoonWaningGibbous4,
    MoonWaningGibbous5,
    MoonWaningGibbous6,
    MoonThirdQuarter,
    MoonWaningCrescent1,
    MoonWaningCrescent2,
    MoonWaningCrescent3,
    MoonWaningCrescent4,
    MoonWaningCrescent5,
    MoonWaningCrescent6,
    MoonAltNew,
    MoonAltWaxingCrescent1,
    MoonAltWaxingCrescent2,
    MoonAltWaxingCrescent3,
    MoonAltWaxingCrescent4,
    MoonAltWaxingCrescent5,
    MoonAltWaxingCrescent6,
    MoonAltFirstQuarter,
    MoonAltWaxingGibbous1,
    MoonAltWaxingGibbous2,
    MoonAltWaxingGibbous3,
    MoonAltWaxingGibbous4,
    MoonAltWaxingGibbous5,
    MoonAltWaxingGibbous6,
    MoonAltFull,
    MoonAltWaningGibbous1,
    MoonAltWaningGibbous2,
    MoonAltWaningGibbous3,
    MoonAltWaningGibbous4,
    MoonAltWaningGibbous5,
    MoonAltWaningGibbous6,
    MoonAltThirdQuarter,
    MoonAltWaningCrescent1,
    MoonAltWaningCrescent2,
    MoonAltWaningCrescent3,
    MoonAltWaningCrescent4,
    MoonAltWaningCrescent5,
    MoonAltWaningCrescent6,
    Moon0,
    Moon1,
    Moon2,
    Moon3,
    Moon4,
    Moon5,
    Moon6,
    Moon7,
    Moon8,
    Moon9,
    Moon10,
    Moon11,
    Moon12,
    Moon13,
    Moon14,
    Moon15,
    Moon16,
    Moon17,
    Moon18,
    Moon19,
    Moon20,
    Moon21,
    Moon22,
    Moon23,
    Moon24,
    Moon25,
    Moon26,
    Moon27,
}


impl Moon {
    pub fn icon(&self) -> &'static str {
        /*
        const MyMoon: Vec<&str> = vec![
            "\u{f095}",
            "\u{f096}",
            "\u{f097}",
            "\u{f098}",
            "\u{f099}",
            "\u{f09a}",
            "\u{f09b}",
            "\u{f09c}",
            "\u{f09d}",
            "\u{f09e}",
            "\u{f09f}",
            "\u{f0a0}",
            "\u{f0a1}",
            "\u{f0a2}",
            "\u{f0a3}",
            "\u{f0a4}",
            "\u{f0a5}",
            "\u{f0a6}",
            "\u{f0a7}",
            "\u{f0a8}",
            "\u{f0a9}",
            "\u{f0aa}",
            "\u{f0ab}",
            "\u{f0ac}",
            "\u{f0ad}",
            "\u{f0ae}",
            "\u{f0af}",
            "\u{f0b0}",
            ];
            */
        use self::Moon::*;
        match *self {
            MoonNew => "\u{f095}",
            MoonWaxingCrescent1 => "\u{f096}",
            MoonWaxingCrescent2 => "\u{f097}",
            MoonWaxingCrescent3 => "\u{f098}",
            MoonWaxingCrescent4 => "\u{f099}",
            MoonWaxingCrescent5 => "\u{f09a}",
            MoonWaxingCrescent6 => "\u{f09b}",
            MoonFirstQuarter => "\u{f09c}",
            MoonWaxingGibbous1 => "\u{f09d}",
            MoonWaxingGibbous2 => "\u{f09e}",
            MoonWaxingGibbous3 => "\u{f09f}",
            MoonWaxingGibbous4 => "\u{f0a0}",
            MoonWaxingGibbous5 => "\u{f0a1}",
            MoonWaxingGibbous6 => "\u{f0a2}",
            MoonFull => "\u{f0a3}",
            MoonWaningGibbous1 => "\u{f0a4}",
            MoonWaningGibbous2 => "\u{f0a5}",
            MoonWaningGibbous3 => "\u{f0a6}",
            MoonWaningGibbous4 => "\u{f0a7}",
            MoonWaningGibbous5 => "\u{f0a8}",
            MoonWaningGibbous6 => "\u{f0a9}",
            MoonThirdQuarter => "\u{f0aa}",
            MoonWaningCrescent1 => "\u{f0ab}",
            MoonWaningCrescent2 => "\u{f0ac}",
            MoonWaningCrescent3 => "\u{f0ad}",
            MoonWaningCrescent4 => "\u{f0ae}",
            MoonWaningCrescent5 => "\u{f0af}",
            MoonWaningCrescent6 => "\u{f0b0}",
            MoonAltNew => "\u{f0eb}",
            MoonAltWaxingCrescent1 => "\u{f0d0}",
            MoonAltWaxingCrescent2 => "\u{f0d1}",
            MoonAltWaxingCrescent3 => "\u{f0d2}",
            MoonAltWaxingCrescent4 => "\u{f0d3}",
            MoonAltWaxingCrescent5 => "\u{f0d4}",
            MoonAltWaxingCrescent6 => "\u{f0d5}",
            MoonAltFirstQuarter => "\u{f0d6}",
            MoonAltWaxingGibbous1 => "\u{f0d7}",
            MoonAltWaxingGibbous2 => "\u{f0d8}",
            MoonAltWaxingGibbous3 => "\u{f0d9}",
            MoonAltWaxingGibbous4 => "\u{f0da}",
            MoonAltWaxingGibbous5 => "\u{f0db}",
            MoonAltWaxingGibbous6 => "\u{f0dc}",
            MoonAltFull => "\u{f0dd}",
            MoonAltWaningGibbous1 => "\u{f0de}",
            MoonAltWaningGibbous2 => "\u{f0df}",
            MoonAltWaningGibbous3 => "\u{f0e0}",
            MoonAltWaningGibbous4 => "\u{f0e1}",
            MoonAltWaningGibbous5 => "\u{f0e2}",
            MoonAltWaningGibbous6 => "\u{f0e3}",
            MoonAltThirdQuarter => "\u{f0e4}",
            MoonAltWaningCrescent1 => "\u{f0e5}",
            MoonAltWaningCrescent2 => "\u{f0e6}",
            MoonAltWaningCrescent3 => "\u{f0e7}",
            MoonAltWaningCrescent4 => "\u{f0e8}",
            MoonAltWaningCrescent5 => "\u{f0e9}",
            MoonAltWaningCrescent6 => "\u{f0ea}",
            Moon0 => "\u{f095}",
            Moon1 => "\u{f096}",
            Moon2 => "\u{f097}",
            Moon3 => "\u{f098}",
            Moon4 => "\u{f099}",
            Moon5 => "\u{f09a}",
            Moon6 => "\u{f09b}",
            Moon7 => "\u{f09c}",
            Moon8 => "\u{f09d}",
            Moon9 => "\u{f09e}",
            Moon10 => "\u{f09f}",
            Moon11 => "\u{f0a0}",
            Moon12 => "\u{f0a1}",
            Moon13 => "\u{f0a2}",
            Moon14 => "\u{f0a3}",
            Moon15 => "\u{f0a4}",
            Moon16 => "\u{f0a5}",
            Moon17 => "\u{f0a6}",
            Moon18 => "\u{f0a7}",
            Moon19 => "\u{f0a8}",
            Moon20 => "\u{f0a9}",
            Moon21 => "\u{f0aa}",
            Moon22 => "\u{f0ab}",
            Moon23 => "\u{f0ac}",
            Moon24 => "\u{f0ad}",
            Moon25 => "\u{f0ae}",
            Moon26 => "\u{f0af}",
            Moon27 => "\u{f0b0}",
        }
    }

    pub fn description(&self) -> &'static str {
        use self::Moon::*;
        match *self {
            MoonNew => "wi-moon-new",
            MoonWaxingCrescent1 => "wi-moon-waxing-crescent-1",
            MoonWaxingCrescent2 => "wi-moon-waxing-crescent-2",
            MoonWaxingCrescent3 => "wi-moon-waxing-crescent-3",
            MoonWaxingCrescent4 => "wi-moon-waxing-crescent-4",
            MoonWaxingCrescent5 => "wi-moon-waxing-crescent-5",
            MoonWaxingCrescent6 => "wi-moon-waxing-crescent-6",
            MoonFirstQuarter => "wi-moon-first-quarter",
            MoonWaxingGibbous1 => "wi-moon-waxing-gibbous-1",
            MoonWaxingGibbous2 => "wi-moon-waxing-gibbous-2",
            MoonWaxingGibbous3 => "wi-moon-waxing-gibbous-3",
            MoonWaxingGibbous4 => "wi-moon-waxing-gibbous-4",
            MoonWaxingGibbous5 => "wi-moon-waxing-gibbous-5",
            MoonWaxingGibbous6 => "wi-moon-waxing-gibbous-6",
            MoonFull => "wi-moon-full",
            MoonWaningGibbous1 => "wi-moon-waning-gibbous-1",
            MoonWaningGibbous2 => "wi-moon-waning-gibbous-2",
            MoonWaningGibbous3 => "wi-moon-waning-gibbous-3",
            MoonWaningGibbous4 => "wi-moon-waning-gibbous-4",
            MoonWaningGibbous5 => "wi-moon-waning-gibbous-5",
            MoonWaningGibbous6 => "wi-moon-waning-gibbous-6",
            MoonThirdQuarter => "wi-moon-third-quarter",
            MoonWaningCrescent1 => "wi-moon-waning-crescent-1",
            MoonWaningCrescent2 => "wi-moon-waning-crescent-2",
            MoonWaningCrescent3 => "wi-moon-waning-crescent-3",
            MoonWaningCrescent4 => "wi-moon-waning-crescent-4",
            MoonWaningCrescent5 => "wi-moon-waning-crescent-5",
            MoonWaningCrescent6 => "wi-moon-waning-crescent-6",
            MoonAltNew => "wi-moon-alt-new",
            MoonAltWaxingCrescent1 => "wi-moon-alt-waxing-crescent-1",
            MoonAltWaxingCrescent2 => "wi-moon-alt-waxing-crescent-2",
            MoonAltWaxingCrescent3 => "wi-moon-alt-waxing-crescent-3",
            MoonAltWaxingCrescent4 => "wi-moon-alt-waxing-crescent-4",
            MoonAltWaxingCrescent5 => "wi-moon-alt-waxing-crescent-5",
            MoonAltWaxingCrescent6 => "wi-moon-alt-waxing-crescent-6",
            MoonAltFirstQuarter => "wi-moon-alt-first-quarter",
            MoonAltWaxingGibbous1 => "wi-moon-alt-waxing-gibbous-1",
            MoonAltWaxingGibbous2 => "wi-moon-alt-waxing-gibbous-2",
            MoonAltWaxingGibbous3 => "wi-moon-alt-waxing-gibbous-3",
            MoonAltWaxingGibbous4 => "wi-moon-alt-waxing-gibbous-4",
            MoonAltWaxingGibbous5 => "wi-moon-alt-waxing-gibbous-5",
            MoonAltWaxingGibbous6 => "wi-moon-alt-waxing-gibbous-6",
            MoonAltFull => "wi-moon-alt-full",
            MoonAltWaningGibbous1 => "wi-moon-alt-waning-gibbous-1",
            MoonAltWaningGibbous2 => "wi-moon-alt-waning-gibbous-2",
            MoonAltWaningGibbous3 => "wi-moon-alt-waning-gibbous-3",
            MoonAltWaningGibbous4 => "wi-moon-alt-waning-gibbous-4",
            MoonAltWaningGibbous5 => "wi-moon-alt-waning-gibbous-5",
            MoonAltWaningGibbous6 => "wi-moon-alt-waning-gibbous-6",
            MoonAltThirdQuarter => "wi-moon-alt-third-quarter",
            MoonAltWaningCrescent1 => "wi-moon-alt-waning-crescent-1",
            MoonAltWaningCrescent2 => "wi-moon-alt-waning-crescent-2",
            MoonAltWaningCrescent3 => "wi-moon-alt-waning-crescent-3",
            MoonAltWaningCrescent4 => "wi-moon-alt-waning-crescent-4",
            MoonAltWaningCrescent5 => "wi-moon-alt-waning-crescent-5",
            MoonAltWaningCrescent6 => "wi-moon-alt-waning-crescent-6",
            Moon0 => "wi-moon-0",
            Moon1 => "wi-moon-1",
            Moon2 => "wi-moon-2",
            Moon3 => "wi-moon-3",
            Moon4 => "wi-moon-4",
            Moon5 => "wi-moon-5",
            Moon6 => "wi-moon-6",
            Moon7 => "wi-moon-7",
            Moon8 => "wi-moon-8",
            Moon9 => "wi-moon-9",
            Moon10 => "wi-moon-10",
            Moon11 => "wi-moon-11",
            Moon12 => "wi-moon-12",
            Moon13 => "wi-moon-13",
            Moon14 => "wi-moon-14",
            Moon15 => "wi-moon-15",
            Moon16 => "wi-moon-16",
            Moon17 => "wi-moon-17",
            Moon18 => "wi-moon-18",
            Moon19 => "wi-moon-19",
            Moon20 => "wi-moon-20",
            Moon21 => "wi-moon-21",
            Moon22 => "wi-moon-22",
            Moon23 => "wi-moon-23",
            Moon24 => "wi-moon-24",
            Moon25 => "wi-moon-25",
            Moon26 => "wi-moon-26",
            Moon27 => "wi-moon-27",
        }
    }

}

pub fn moon_phase(phase: f64) -> Moon {
    match (phase * 28f64).round() as u32 {
        1 => Moon::Moon0,
        2 => Moon::Moon1,
        3 => Moon::Moon2,
        4 => Moon::Moon3,
        5 => Moon::Moon4,
        6 => Moon::Moon5,
        7 => Moon::Moon6,
        8 => Moon::Moon7,
        9 => Moon::Moon8,
        10 => Moon::Moon9,
        11 => Moon::Moon10,
        12 => Moon::Moon11,
        13 => Moon::Moon12,
        14 => Moon::Moon13,
        15 => Moon::Moon14,
        16 => Moon::Moon15,
        17 => Moon::Moon16,
        18 => Moon::Moon17,
        19 => Moon::Moon18,
        20 => Moon::Moon19,
        21 => Moon::Moon20,
        22 => Moon::Moon21,
        23 => Moon::Moon22,
        24 => Moon::Moon23,
        25 => Moon::Moon24,
        26 => Moon::Moon25,
        27 => Moon::Moon26,
        28 => Moon::Moon27,
        _ => Moon::MoonAltFull,
    }
}

impl fmt::Display for Moon {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{}", self.icon())
    }
}

impl fmt::Debug for Moon {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{}: {:?}", self.description(), self.icon())
    }
}
